tmobile/DevEdge-IoTDevKit-ZephyrSDK

- samples/tmo_shell/src/tmo_shell.c
- samples/tmo_shell/src/tmo_sntp.c
- samples/tmo_shell/src/tmo_sntp.h
Added support for interface selection and better error handling.
> samples: Fix tmo shell SNTP

- samples/tmo_shell/src/tmo_bq24250.c
- samples/tmo_shell/src/tmo_shell.c
- samples/tmo_shell/src/tmo_wifi.c
> Minor fixes to get tmo-shell building again

- samples/tmo_shell/src/dfu_rs9116w.c
- samples/tmo_shell/src/tmo_ble_demo.c
- samples/tmo_shell/src/tmo_gnss.c
- samples/tmo_shell/src/tmo_modem.c
- samples/tmo_shell/src/tmo_pm_sys.c
- samples/tmo_shell/src/tmo_shell.c
- samples/tmo_shell/src/tmo_web_demo.c
Fixed issues related to changes resultant from removing devicetree labels
Signed-off-by: Jared Baumann <Jared.Baumann8@t-mobile.com>
> Removed reliance on labels

- samples/tmo_shell/Kconfig
- samples/tmo_shell/src/misc_test.c
- samples/tmo_shell/src/tmo_shell.c
Made manufacturing tests more comprehensive with version checks
> Upgraded manufacturing tests

- samples/tmo_shell/src/misc_test.c
> Fix manufacturing tests in 1.16

- samples/tmo_shell/src/tmo_shell.c
Added check for excessive interface values on socket create commands
> Fixed crash on excessive interface value

- samples/tmo_shell/src/tmo_shell.c
Added command "tmo battery discharge" to discharge battery down to 60%.
> Added battery discharge command for shipment

- samples/tmo_shell/CMakeLists.txt
- samples/tmo_shell/src/led_test.c
- samples/tmo_shell/src/tmo_adc.c
- samples/tmo_shell/src/tmo_adc.h
- samples/tmo_shell/src/tmo_ble_demo.c
- samples/tmo_shell/src/tmo_buzzer.c
- samples/tmo_shell/src/tmo_shell.c
Now using board headers for magic variables for HWID Pin, LED index, Etc
> Added logic to deal with board variants

- samples/tmo_shell/src/tmo_pm.c
- samples/tmo_shell/src/tmo_pm.h
- samples/tmo_shell/src/tmo_shell.c
Added command to lock and unlock the power management states of devices for testing
> Added PM lock and unlock commands

- samples/tmo_shell/src/tmo_shell.c
This improves the battery discharge messages and logic
> Improve battery discharge messages and logic

- samples/lis2dw12_sample/src/main.c
Included LIS2DW12 specific header
> Added necessary header to LIS2DW12 sample

- samples/lis2dw12_sample/src/main.c
Signed-off-by: Kevin King <kevin.king101@t-mobile.com>
> lis2dw12 Accelerator Demo updated from last commit PR.

- samples/lis2dw12_sample/src/main.c
Add lis2dw12.h header to sample
> Fix lis2dw12 sample

- samples/tmo_shell/CMakeLists.txt
Set default extra modules in tmo shell to fix build
> Fix tmo shell build

- zephyr/module.yml
This removes board_root from modules.yml
> Remove board_root

- samples/tmo_shell/src/tmo_web_demo.c
This checks for presence of the pressure sensor when generating json payload for web app
> Check for pressure sensor in web app

- samples/tmo_shell/src/tmo_adc.c
Changed ADC code to enable the voltage divider only on read.
> Changed ADC_SENSE_EN to not be set at all times

- samples/tmo_shell/src/tmo_shell.c
Added tmo shell command for setting eDRX PTW
> Add tmo modem ptw command

- samples/tmo_shell/src/tmo_shell.c
- samples/tmo_shell/src/tmo_wifi.c
Fixed warnings in tmo-shell from shell_help
> Fix warnings in tmo-shell

- samples/tmo_shell/src/tmo_ble_demo.c
Removed check for battery is present for reading battery percentage over ble
> Removed extraneous check from battery logic

- samples/tmo_shell/src/tmo_dfu_download.c
> Fixed typo in sprintf

- dfu_gecko/dfu_gecko_lib.h
- samples/tmo_shell/src/dfu_murata_1sc.c
- samples/tmo_shell/src/dfu_murata_1sc.h
- samples/tmo_shell/src/tmo_certs.c
- samples/tmo_shell/src/tmo_dfu_download.h
- samples/tmo_shell/src/tmo_http_request.c
- samples/tmo_shell/src/tmo_shell.c
> Fix various DFU issues

- samples/bluetooth/peripheral_sc_only/src/main.c
- samples/bluetooth/sc_extensive_test/src/main.c
Fixed bluetooth SC samples to build in modern zephyr.
> Fixed bluetooth SC samples

- samples/tmo_shell/src/dfu_murata_1sc.c
- samples/tmo_shell/src/dfu_rs9116w.c
- samples/tmo_shell/src/tmo_shell.c
This has minor improvements to the 'tmo dfu version <1 and 2> commands
> Improve tmo dfu version

- samples/tmo_shell/src/tmo_sntp.c
Use the same basic pattern as in date_service.c.
> samples: tmo_sntp: Remove TIME_GECKO_RTCC and doc/finish persistence.

- samples/tmo_shell/src/misc_test.c
- samples/tmo_shell/src/tmo_adc.c
Fixed warnings and an ADC millivolt conversion error on HWID.
> Fixed warnings and a small error

- samples/tmo_shell/src/tmo_shell.c
Fixed typo in socket receive command.
> Fixed typo

- samples/tmo_shell/src/tmo_ble_demo.c
- samples/tmo_shell/src/tmo_shell.c
Added ability to set ibeacon parameters to the ibeacon command.
> Added custom ibeacon functionality to tmo shell

- samples/as6212_sample/src/main.c
Removed erroneous message generated on wake.
> Fixed error message in as6212 sample

- samples/tmo_shell/src/tmo_certs.c
- samples/tmo_shell/src/tmo_dfu_download.c
- samples/tmo_shell/src/tmo_dfu_download.h
- samples/tmo_shell/src/tmo_http_request.c
- samples/tmo_shell/src/tmo_http_request.h
- samples/tmo_shell/src/tmo_shell.c
Added logic to use authorization keys with DFU downloads.
> Add auth key to dfu downloads

- samples/tmo_shell/src/tmo_gnss.c
- samples/tmo_shell/src/tmo_gnss.h
- samples/tmo_shell/src/tmo_shell.c
Added fix valid field to properly determine if current fix is valid or not.
> Added fix valid field to gnss values

- samples/tmo_shell/src/tmo_battery_ctrl.c
This improves the battery charge/discharge tables
> Improve battery charge/discharge tables

- samples/tmo_shell/src/tmo_http_request.c
Modified cert store to use loaded cert if applicable for functioning with alternate endpoints.
> Fixed json to work with cert store certs

- samples/tmo_shell/src/tmo_shell.c
This checks for battery attached in the battery voltage and percentage commands.
> Check for battery attached

- samples/tmo_shell/src/tmo_shell.c
Added warning for attempting to send SMS larger than the configured maximum size.
> Added warning for long SMS

- scripts/midi_tone_bin.py
- scripts/requirements.txt
Added script for converting midi to the tone format used by the jingle player
> Added midi conversion script

- samples/tmo_shell/src/tmo_shell.c
Temporarily disabled verification for secure connect on modem
> Fix secure connect on modem

- samples/tmo_shell/src/tmo_adc.c
- samples/tmo_shell/src/tmo_sntp.c
This fixes an ADC build warning
> Fix ADC build warning

- samples/tmo_shell/src/misc_test.c
- samples/tmo_shell/src/tmo_gnss.c
This adds gnss version to 'tmo test mfg all'
> Add gnss version to mfg test

- samples/tmo_shell/Kconfig
- samples/tmo_shell/src/tmo_ble_demo.c
- samples/tmo_shell/src/tmo_modem.c
- samples/tmo_shell/src/tmo_shell.c
- samples/tmo_shell/src/tmo_web_demo.c
Added functionality to test the SMS recv callback in tmo shell.
> Added async SMS function to tmo shell

- samples/button_press_cb/CMakeLists.txt
- samples/button_press_cb/Kconfig
- samples/button_press_cb/README.txt
- samples/button_press_cb/prj.conf
- samples/button_press_cb/src/button.c
- samples/button_press_cb/src/button.h
- samples/button_press_cb/src/main.c
This adds the functionality of a callback for user button presses, and gives information on the timestamp, duration and type of button press.
> Cfspdk 1075 button press cb

- samples/tmo_shell/src/tmo_shell.c
Added missing check for SMS enable
> Fixed build with SMS disabled

- samples/tmo_shell/src/tmo_http_request.c
Added packet timeout to http download
> Address large download issues

- samples/tmo_shell/src/tmo_http_request.c
Changed retry behavior to reset retry counter on data receipt.
> Change retry behavior

- samples/tmo_shell/src/tmo_ping.c
Fixed issue where command wasn't returning on errors.
> Fixed crash on ping count zero

- samples/tmo_shell/src/tmo_shell.c
Before this commit, 
Passing in a random string value to `tmo_shell` commands that expect integer values would probably be passed undetected (was verified for socket sub commands). This was an erroneous behavior.
After this commit,
The `tmo_strtol` wrapper function will make sure to clear `errno` before calling the library `strtol` function and also perform some basic error handling. 
The application code will check the `errno` value after calling `tmo_strtol()` and return the `-errno` after printing some suitable error message on the shell.
> CFSDPK-1282: Added a wrapper for strtol() in tmo_shell

- samples/tmo_shell/src/tmo_ble_demo.c
- samples/tmo_shell/src/tmo_http_request.c
- samples/tmo_shell/src/tmo_wifi.c
These changes need work with the appropriate experts.
> Make stable release of tmo_shell on DevEdge

- samples/tmo_shell/src/misc_test.c
This is the last of the known errors, but I'm still getting a fail from tmo test mfg all
> samples: tmo_shell: Fix lc709204f conditionals in src/misc_test.c
