- samples/tmo_shell/src/tmo_shell.h
This adds '#if defined's around the zsock_socket_ext function
> Add '#if defined's around zsock_socket_ext

- samples/tmo_shell/src/tmo_shell.c
Fixed warnings generated when building tmo shell with newer versions of the Zephyr SDK.
> Address tmo-shell warnings in HEAD 

- samples/tmo_shell/src/tmo_modem.c
Removed reference to the deprecated zephyr.h header file
Signed-off-by: Jared Baumann <Jared.Baumann8@t-mobile.com>
> Fixed tmo_modem.c includes

- samples/tmo_shell/src/tmo_shell.c
added missing FLASH CTRL device from rebase.
> fixes missing Gecko FLASH CTRL device at run time.

- samples/tmo_shell/src/tmo_modem.c
- samples/tmo_shell/src/tmo_shell.c
- samples/tmo_shell/src/tmo_web_demo.c
Properly checks for murata interface for modem command as well as others
> Fixed flipped logic for murata checks

- samples/tmo_shell/boards/tmo_dev_edge_mcuboot.overlay
- samples/tmo_shell/overlay-bl.conf
- samples/tmo_shell/overlay-slot.conf
Fixed configs to eliminate bootloader CMake warnings.
> Fix warnings on bootloader build

- samples/tmo_shell/src/dfu_rs9116w.c
Fixed DFU build issues caused by update to WiSeConnect 2.7
> Fix issues in DFU introduced in WiSeConnect 2.7

- samples/tmo_shell/src/tmo_pm.c
Added check for current state to suspend before off/turn on before resume.
> Fixed tmo pm off command

- samples/tmo_shell/src/tmo_shell.c
- samples/tmo_shell/src/tmo_shell.h
- samples/tmo_shell/src/tmo_wifi.c
Added command to read the MAC address from the RS9116 WiFi chip.
> Added WiFi MAC read command

- samples/tmo_shell/src/tmo_shell.c
Disabled the sys_pm standby command awaiting power control changes from upstream.
> Temporarily disabled standby command

- samples/tmo_shell/src/tmo_ble_demo.c
Combine two connectivity services in order to conserve the limited service handles.
> Combine services to increase available handles

- samples/tmo_shell/src/tmo_pm_sys.c
Fixed issue where devices would not turn off on calling the sys_pm off/ sys_pm fulloff commands
> Fixed off/full off

- samples/tmo_shell/src/tmo_http_request.c
Fixed issue where download resume would fail on the murata modem.
> Fixed download resume logic on modem

- samples/tmo_shell/src/tmo_http_request.c
Fixed issue where headers smaller than size of buffer would lead to a hang.
> Fixed issues with header parsing

- samples/tmo_shell/src/tmo_ping.c
- samples/tmo_shell/src/tmo_shell.c
Fix includes for tmo-shell so that we can build with HEAD
> Fix tmo shell build in HEAD

- samples/lis2dw12_sample/src/main.c
Signed-off-by: Kevin King <kevin.king101@t-mobile.com>
> fixed ambient temperature in the lis2dw12 sensor sample.

- samples/tmo_shell/src/tmo_ble_demo.c
- samples/tmo_shell/src/tmo_http_request.c
- samples/tmo_shell/src/tmo_modem.c
- samples/tmo_shell/src/tmo_web_demo.c
Removed includes referencing deprecated fnctl location, replacing with new path.
> Fixed old FCNTL paths to eliminate warnings

- samples/tmo_shell/src/tmo_ble_demo.c
- samples/tmo_shell/src/tmo_shell.c
This adds a setpoint to battery discharge command. If not specified, the default value of 60 is used.
> Add setpoint to battery discharge

- samples/tmo_shell/src/tmo_shell.c
Removed unused 3312 and 3314 timers and added support for full range of T3412 and T3324 timers.
> Fixed PSM set command

- samples/tmo_shell/src/dfu_murata_1sc.c
- samples/tmo_shell/src/tmo_dfu_download.c
- samples/tmo_shell/src/tmo_dfu_download.h
- samples/tmo_shell/src/tmo_shell.c
There was some file name changes to the modem and some clean up done in the modem code commented out code removed and comments fixed per zephyr standards.
Signed-off-by: Kim Mansfield <kim.mansfield2@t-mobile.com>
> TMO_SHELL: DFU: Clean up and file name changes

- dfu_gecko/dfu_gecko_lib.c
This removes deserialize_magic_hdr function which is no longer used.
> Remove deserialize_magic_hdr

- samples/tmo_shell/src/tmo_ping.c
Fixed handling of invalid count values in the tmo ping command
> Fixed ping in tmo-shell

- samples/tmo_shell/src/tmo_ble_demo.c
LED is now turned off on connect so that the LED will be in a known state for the BLE interface.
> Minor fix for BLE led logic

- samples/push_button_sample/Kconfig
- samples/push_button_sample/prj.conf
- samples/push_button_sample/src/main.c
1. Fix defect causing an endless loop
2. Remove a superfluous parameter passed to the GPIO configuration
routine
3. Add a configuration option facilitating an option for an additional
pull-up resistor
> Fix pushbutton defect

- samples/tmo_shell/src/tmo_adc.c
This removes the exponential filter used for battery percentages.
> Remove exponential filter

- samples/tmo_shell/src/tmo_ble_demo.c
- samples/tmo_shell/src/tmo_wifi.c
This fixes some build warnings related to unused parameters
> Fix build warnings with unused parameters

- samples/tmo_shell/src/tmo_shell.c
- samples/tmo_shell/src/tmo_sntp.c
Better error descrioption for failed `tmo modem` command that results in `errno = 12`, meaning no sockets available.
> Better error description for failed tmo modem

- samples/tmo_shell/src/tmo_shell.c
Previous to this commit, 
If the user performs an action on a non-existent socket in excess of max unsigned integer size it will return the value of 2147483647 incorrectly.
After this commit, the passed in socket num will be correctly displayed in the error message. 
As well as, added a check to determine if passed socket num is not an integer and returns the set errno appropriately.
> Correct socket num description in error string

- samples/tmo_shell/src/tmo_adc.c
- samples/tmo_shell/src/tmo_adc.h
- samples/tmo_shell/src/tmo_shell.c
Presumably, defers to the APIs in tmo_devices.
> Make tmo_shell ADC activity defer to external.
